### ISSUE TITLE
Possible typo in error message

### ISSUE THREAD

**Issue by SolidOrange** [yngvem/group-lasso#19]
Hello, I just got the following error message while trying to fit a LogisticGroupLasso:

```
RuntimeWarning: The FISTA iterations did not converge to a sufficient minimum.
You used subsampling then this is expected, otherwise,try to increase the number of iterations or decreasing the tolerance.
```

Shouldn't this recommend _increasing_ the tolerance to reach convergence sooner?

**Comment by yngvem** [comment]
Thank you! This will be fixed in the next version
