### ISSUE TITLE
can your code find these groups by itself?

### ISSUE THREAD

**Issue by Sandy4321** [yngvem/group-lasso#3]
may you help understand what to do if I do not know how many groups  there in  data?
can your code find these groups by itself?
what would be for overlapping groups like your refrences
https://papers.nips.cc/paper/4275-efficient-methods-for-overlapping-group-lasso.pdf
https://www.researchgate.net/publication/46582615_Fast_Overlapping_Group_Lasso

**Comment by yngvem** [comment]
Group lasso is the regulariser you use if you know what the groups are and want to impose that information on the model. If you don't know the groups, then I guess you could cluster the groups first.

As to your reference, that is for group lasso with overlapping group, which may be useful if your covariates are not in disjoint groups. However, you should still know what the groups are to use group lasso.

**Comment by Sandy4321** [comment]
you don't know the groups, then I guess you could cluster the groups first.
I see
Do you know some code examples for this kind of case to use clusters

**Comment by yngvem** [comment]
No I do not know of any code examples for that, but it should be quite trivial to do it. You can for example google feature clustering or biclustering.
