### ISSUE TITLE
About Group lasso logistic regression using PGD

### ISSUE THREAD

**Issue by GuoBruce** [yngvem/group-lasso#33]
Thanks for your contribution in group lasso question! What should I do if I want to solve Group lasso logistic regression using proximal gradident descent method? Can you give me some advice?

**Comment by yngvem** [comment]
This library used FISTA, which is a Nesterov accelerated proximal gradient method, so I guess you could find most of what you need in the source code. Though I'm not sure why you would want to use a non-accelerated version and not just this code...
